---
- name: Install apache
  yum:
    name: httpd
    state: present
  become: yes

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Start apache
  service:
    name: httpd
    state: started

- name: Post Installation Message
  debug:
    msg: "Apache is installed and running."

